apiVersion: v2
name: cx-decentral-dtr-setup
description: A Helm chart that allows to easily set up a decentral registry behind an EDC

type: application

version: 0.1.0

appVersion: "1.16.0"


dependencies:
  - name: registry
    repository: https://eclipse-tractusx.github.io/sldt-digital-twin-registry
    version: 0.3.0
  - name: tractusx-connector
    alias: provider
    condition: provider.enabled
    repository: https://catenax-ng.github.io/product-edc
    version: 0.2.0
  - name: tractusx-connector
    alias: consumer
    condition: consumer.enabled
    repository: https://catenax-ng.github.io/product-edc
    version: 0.2.0
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.1.5
  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.23.0
    condition: vault.enabled
  - name: omejdn-server
    alias: daps
    repository: https://catenax-ng.github.io/product-DAPS/
    version: 1.7.1
    condition: daps.enabled